name: Publish calendar

on:
  workflow_dispatch:
  release:
    types: [ published ]
  schedule:
    - cron: '37 * 1-15 1 *'  # AGDQ - January
    - cron: '37 * 19-30 6 *' # SGDQ - June
    - cron: '37 * 1-3 7 *'   # SGDQ - July

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/gdq.ics

    runs-on: ubuntu-latest

    steps:
      - name: Download latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: GamesDoneQuickCalendarFactory-linux-x64
          target: './GamesDoneQuickCalendarFactory'

      - name: Set executable bit
        run: chmod +x GamesDoneQuickCalendarFactory

      - name: Generate calendar
        run: ./GamesDoneQuickCalendarFactory

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2

      - name: Prepare Pages files
        run: |
          mkdir pages
          cp gdq.ics pages

      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: pages
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
